import type { ServiceMode } from './types';

export type CategoryHeuristic = {
  slug: string;
  name: string;
  icon: string;
  preferredMode: ServiceMode;
  keywords: string[];
};

export const CATEGORY_HEURISTICS: CategoryHeuristic[] = [
  {
    slug: 'plomeria',
    name: 'Plomeria',
    icon: 'Droplets',
    preferredMode: 'immediate',
    keywords: [
      'agua',
      'canilla',
      'cocina',
      'destapar',
      'flexible',
      'inodoro',
      'pierde',
      'plomero',
      'sanitario',
      'termotanque',
    ],
  },
  {
    slug: 'electricidad',
    name: 'Electricidad',
    icon: 'Zap',
    preferredMode: 'immediate',
    keywords: [
      'cable',
      'corto',
      'electricidad',
      'enchufe',
      'habitacion',
      'luz',
      'llave',
      'no tengo',
      'termica',
    ],
  },
  {
    slug: 'gas',
    name: 'Gasista',
    icon: 'Flame',
    preferredMode: 'scheduled',
    keywords: ['calefon', 'estufa', 'gas', 'gasista', 'matricula', 'olor'],
  },
  {
    slug: 'cerrajeria',
    name: 'Cerrajeria',
    icon: 'KeyRound',
    preferredMode: 'immediate',
    keywords: ['afuera', 'cerradura', 'cerrajero', 'llave', 'puerta'],
  },
  {
    slug: 'limpieza',
    name: 'Limpieza',
    icon: 'Sparkles',
    preferredMode: 'scheduled',
    keywords: ['limpieza', 'limpiar', 'profunda', 'semanal'],
  },
  {
    slug: 'pintura',
    name: 'Pintura',
    icon: 'Paintbrush',
    preferredMode: 'quote',
    keywords: ['departamento', 'pared', 'pintar', 'pintura', 'techo'],
  },
  {
    slug: 'jardin',
    name: 'Jardinería',
    icon: 'Flower2',
    preferredMode: 'scheduled',
    keywords: ['cesped', 'jardin', 'jardineria', 'plantas', 'poda'],
  },
  {
    slug: 'aire',
    name: 'Aire acondicionado',
    icon: 'Wind',
    preferredMode: 'scheduled',
    keywords: ['aire', 'split', 'frio', 'calor', 'filtro'],
  },
  {
    slug: 'electro',
    name: 'Electrodomésticos',
    icon: 'WashingMachine',
    preferredMode: 'scheduled',
    keywords: ['heladera', 'lavarropas', 'microondas', 'no enfria'],
  },
  {
    slug: 'carpinteria',
    name: 'Carpinteria',
    icon: 'Hammer',
    preferredMode: 'quote',
    keywords: ['madera', 'mueble', 'placard', 'puerta', 'carpintero'],
  },
  {
    slug: 'albanileria',
    name: 'Albanileria',
    icon: 'BrickWall',
    preferredMode: 'quote',
    keywords: ['albanil', 'pared', 'reforma', 'revoque', 'obra'],
  },
  {
    slug: 'mudanzas',
    name: 'Mudanzas',
    icon: 'Truck',
    preferredMode: 'quote',
    keywords: ['camion', 'flete', 'mudanza', 'mudar'],
  },
  {
    slug: 'fumigacion',
    name: 'Fumigacion',
    icon: 'Bug',
    preferredMode: 'scheduled',
    keywords: ['cucaracha', 'fumigar', 'hormigas', 'insectos', 'ratas'],
  },
  {
    slug: 'tecnologia',
    name: 'PC y tecnología',
    icon: 'MonitorCog',
    preferredMode: 'scheduled',
    keywords: ['computadora', 'internet', 'notebook', 'pc', 'wifi'],
  },
  {
    slug: 'pileta',
    name: 'Piletas',
    icon: 'Waves',
    preferredMode: 'scheduled',
    keywords: ['bomba', 'cloro', 'pileta', 'piscina', 'verde'],
  },
  {
    slug: 'arquitectura',
    name: 'Arquitectura',
    icon: 'Building2',
    preferredMode: 'quote',
    keywords: ['ampliacion', 'arquitecto', 'arquitectura', 'obra', 'plano', 'planos', 'proyecto', 'regularizacion', 'reforma', 'render'],
  },
  {
    slug: 'ingenieria',
    name: 'Ingeniería',
    icon: 'BriefcaseBusiness',
    preferredMode: 'quote',
    keywords: ['calculo', 'civil', 'estructura', 'estructural', 'higiene', 'ingenieria', 'ingeniero', 'peritaje', 'seguridad'],
  },
  {
    slug: 'diseno_interiores',
    name: 'Diseño de interiores',
    icon: 'Palette',
    preferredMode: 'quote',
    keywords: ['ambientacion', 'decoracion', 'diseno interior', 'interiores', 'mobiliario', 'terminaciones'],
  },
  {
    slug: 'fotografia',
    name: 'Fotografía',
    icon: 'Camera',
    preferredMode: 'scheduled',
    keywords: ['evento', 'foto', 'fotografia', 'fotografo', 'producto', 'retrato', 'video'],
  },
  {
    slug: 'profesores_particulares',
    name: 'Profesores particulares',
    icon: 'GraduationCap',
    preferredMode: 'scheduled',
    keywords: ['apoyo escolar', 'clase', 'examen', 'ingles', 'matematica', 'profesor', 'universitario'],
  },
  {
    slug: 'soporte_remoto',
    name: 'Soporte tecnológico remoto',
    icon: 'MonitorCog',
    preferredMode: 'scheduled',
    keywords: ['asistencia remota', 'backup', 'celular', 'notebook', 'pc', 'software', 'soporte remoto', 'wifi'],
  },
  {
    slug: 'mecanica_automotor',
    name: 'Mecánica automotor',
    icon: 'CarFront',
    preferredMode: 'scheduled',
    keywords: ['auto', 'automotor', 'bateria', 'frenos', 'mecanico', 'motor', 'service'],
  },
  {
    slug: 'gomeria',
    name: 'Gomería',
    icon: 'CircleGauge',
    preferredMode: 'immediate',
    keywords: ['alineacion', 'auxilio', 'balanceo', 'cubierta', 'goma', 'gomeria', 'pinchadura', 'rueda'],
  },
  {
    slug: 'chapa_pintura_auto',
    name: 'Chapa y pintura',
    icon: 'Car',
    preferredMode: 'quote',
    keywords: ['abolladura', 'auto', 'carroceria', 'chapa', 'pintura auto', 'rayon'],
  },
];

export const statusOrder = [
  'requested',
  'searching_professional',
  'confirmed',
  'professional_en_route',
  'professional_arrived',
  'work_started',
  'completed',
  'paid',
] as const;
