-- MANITO V6 Real baseline for Supabase.
-- Apply on a fresh Supabase project, or reset the previous prototype first.

create extension if not exists pgcrypto;
create schema if not exists private;

revoke all on schema private from public, anon, authenticated;
grant usage on schema private to authenticated;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text not null default '',
  role text not null default 'client'
    check (role in ('client', 'professional', 'admin')),
  phone text,
  city text,
  is_available boolean not null default false,
  lat double precision,
  lng double precision,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text not null,
  emoji text not null default 'wrench',
  base_price numeric(12, 2),
  active boolean not null default true
);

create table if not exists public.professional_services (
  professional_id uuid not null references public.profiles(id) on delete cascade,
  service_id bigint not null references public.services(id) on delete cascade,
  price_from numeric(12, 2),
  primary key (professional_id, service_id)
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references public.profiles(id) on delete restrict,
  professional_id uuid references public.profiles(id) on delete set null,
  service_id bigint not null references public.services(id) on delete restrict,
  description text not null,
  address text not null,
  mode text not null default 'immediate'
    check (mode in ('immediate', 'scheduled', 'quote')),
  scheduled_at timestamptz,
  status text not null default 'open'
    check (status in ('open', 'accepted', 'en_camino', 'en_sitio', 'completed', 'cancelled')),
  price numeric(12, 2),
  client_lat double precision,
  client_lng double precision,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  accepted_at timestamptz,
  completed_at timestamptz
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists idx_orders_client
  on public.orders(client_id, created_at desc);
create index if not exists idx_orders_professional
  on public.orders(professional_id, created_at desc);
create index if not exists idx_orders_open
  on public.orders(status, service_id, created_at desc)
  where status = 'open';
create index if not exists idx_messages_order
  on public.messages(order_id, created_at);

insert into public.services (slug, name, emoji, base_price) values
  ('plomeria', 'Plomeria', 'wrench', 18000),
  ('electricidad', 'Electricidad', 'bolt', 20000),
  ('gas', 'Gasista', 'flame', 22000),
  ('cerrajeria', 'Cerrajeria', 'key', 19000),
  ('limpieza', 'Limpieza', 'sparkles', 15000),
  ('pintura', 'Pintura', 'paint', 25000),
  ('jardineria', 'Jardineria', 'leaf', 16000),
  ('aire', 'Aire acondicionado', 'snowflake', 24000),
  ('electrodomesticos', 'Electrodomesticos', 'plug', 21000),
  ('carpinteria', 'Carpinteria', 'hammer', 23000)
on conflict (slug) do update set
  name = excluded.name,
  emoji = excluded.emoji,
  base_price = excluded.base_price,
  active = true;

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function public.touch_updated_at() from public, anon, authenticated;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute function public.touch_updated_at();

drop trigger if exists trg_orders_updated_at on public.orders;
create trigger trg_orders_updated_at
before update on public.orders
for each row execute function public.touch_updated_at();

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', ''),
    'client'
  )
  on conflict (id) do update set
    email = excluded.email,
    full_name = case
      when public.profiles.full_name = '' then excluded.full_name
      else public.profiles.full_name
    end;

  return new;
end;
$$;

revoke all on function private.handle_new_user() from public, anon, authenticated;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function private.handle_new_user();

alter table public.profiles enable row level security;
alter table public.services enable row level security;
alter table public.professional_services enable row level security;
alter table public.orders enable row level security;
alter table public.messages enable row level security;

revoke all on public.profiles from anon, authenticated;
revoke all on public.services from anon, authenticated;
revoke all on public.professional_services from anon, authenticated;
revoke all on public.orders from anon, authenticated;
revoke all on public.messages from anon, authenticated;

grant select on public.profiles to authenticated;
grant update (full_name, phone, city, is_available, lat, lng)
  on public.profiles to authenticated;
grant select on public.services to authenticated;
grant select, insert, delete on public.professional_services to authenticated;
grant select, insert on public.orders to authenticated;
grant select, insert on public.messages to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles
for select to authenticated
using (
  id = (select auth.uid())
  or role = 'professional'
);

drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles
for update to authenticated
using (id = (select auth.uid()))
with check (id = (select auth.uid()));

drop policy if exists services_select on public.services;
create policy services_select on public.services
for select to authenticated
using (active = true);

drop policy if exists pro_services_select on public.professional_services;
create policy pro_services_select on public.professional_services
for select to authenticated
using (true);

drop policy if exists pro_services_insert_own on public.professional_services;
create policy pro_services_insert_own on public.professional_services
for insert to authenticated
with check (
  professional_id = (select auth.uid())
  and exists (
    select 1
    from public.profiles p
    where p.id = (select auth.uid())
      and p.role = 'professional'
  )
  and exists (
    select 1
    from public.services s
    where s.id = professional_services.service_id
      and s.active = true
  )
);

drop policy if exists pro_services_delete_own on public.professional_services;
create policy pro_services_delete_own on public.professional_services
for delete to authenticated
using (professional_id = (select auth.uid()));

drop policy if exists orders_select on public.orders;
create policy orders_select on public.orders
for select to authenticated
using (
  client_id = (select auth.uid())
  or professional_id = (select auth.uid())
  or (
    status = 'open'
    and exists (
      select 1
      from public.profiles p
      where p.id = (select auth.uid())
        and p.role = 'professional'
        and p.is_available = true
    )
    and exists (
      select 1
      from public.professional_services ps
      where ps.professional_id = (select auth.uid())
        and ps.service_id = orders.service_id
    )
  )
);

drop policy if exists orders_insert_client on public.orders;
create policy orders_insert_client on public.orders
for insert to authenticated
with check (
  client_id = (select auth.uid())
  and exists (
    select 1
    from public.profiles p
    where p.id = (select auth.uid())
      and p.role = 'client'
  )
);

drop policy if exists messages_select_participants on public.messages;
create policy messages_select_participants on public.messages
for select to authenticated
using (
  exists (
    select 1
    from public.orders o
    where o.id = messages.order_id
      and ((select auth.uid()) = o.client_id or (select auth.uid()) = o.professional_id)
  )
);

drop policy if exists messages_insert_participants on public.messages;
create policy messages_insert_participants on public.messages
for insert to authenticated
with check (
  sender_id = (select auth.uid())
  and exists (
    select 1
    from public.orders o
    where o.id = messages.order_id
      and ((select auth.uid()) = o.client_id or (select auth.uid()) = o.professional_id)
      and o.status <> 'cancelled'
  )
);

create or replace function private.complete_profile_impl(
  p_full_name text,
  p_role text,
  p_phone text default null,
  p_city text default null
)
returns public.profiles
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_role text := lower(btrim(coalesce(p_role, '')));
  v_profile public.profiles;
begin
  if v_uid is null then
    raise exception 'No autenticado';
  end if;

  if nullif(btrim(coalesce(p_full_name, '')), '') is null then
    raise exception 'El nombre es obligatorio';
  end if;

  if v_role not in ('client', 'professional') then
    raise exception 'Rol no permitido';
  end if;

  insert into public.profiles (id, email, full_name, role, phone, city)
  select
    u.id,
    u.email,
    btrim(p_full_name),
    v_role,
    nullif(btrim(coalesce(p_phone, '')), ''),
    nullif(btrim(coalesce(p_city, '')), '')
  from auth.users u
  where u.id = v_uid
  on conflict (id) do update set
    email = coalesce(public.profiles.email, excluded.email),
    full_name = excluded.full_name,
    role = excluded.role,
    phone = excluded.phone,
    city = excluded.city
  returning * into v_profile;

  if v_profile.id is null then
    raise exception 'Usuario no encontrado';
  end if;

  return v_profile;
end;
$$;

create or replace function public.complete_profile(
  p_full_name text,
  p_role text,
  p_phone text default null,
  p_city text default null
)
returns public.profiles
language sql
security invoker
set search_path = public, private
as $$
  select * from private.complete_profile_impl(p_full_name, p_role, p_phone, p_city);
$$;

create or replace function private.accept_order_impl(p_order_id uuid)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_order public.orders;
begin
  if v_uid is null then
    raise exception 'No autenticado';
  end if;

  if not exists (
    select 1
    from public.profiles p
    where p.id = v_uid
      and p.role = 'professional'
      and p.is_available = true
  ) then
    raise exception 'El profesional debe estar disponible';
  end if;

  update public.orders o
  set
    professional_id = v_uid,
    status = 'accepted',
    accepted_at = now(),
    price = coalesce(
      (
        select ps.price_from
        from public.professional_services ps
        where ps.professional_id = v_uid
          and ps.service_id = o.service_id
      ),
      (
        select s.base_price
        from public.services s
        where s.id = o.service_id
      )
    )
  where o.id = p_order_id
    and o.status = 'open'
    and o.professional_id is null
    and exists (
      select 1
      from public.professional_services ps
      where ps.professional_id = v_uid
        and ps.service_id = o.service_id
    )
  returning o.* into v_order;

  if v_order.id is null then
    raise exception 'El pedido ya fue tomado o no corresponde a tus servicios';
  end if;

  return v_order;
end;
$$;

create or replace function public.accept_order(p_order_id uuid)
returns public.orders
language sql
security invoker
set search_path = public, private
as $$
  select * from private.accept_order_impl(p_order_id);
$$;

create or replace function private.advance_order_impl(p_order_id uuid)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_current text;
  v_next text;
  v_order public.orders;
begin
  if v_uid is null then
    raise exception 'No autenticado';
  end if;

  select status into v_current
  from public.orders
  where id = p_order_id
    and professional_id = v_uid
  for update;

  if v_current is null then
    raise exception 'Pedido no encontrado';
  end if;

  v_next := case v_current
    when 'accepted' then 'en_camino'
    when 'en_camino' then 'en_sitio'
    when 'en_sitio' then 'completed'
    else null
  end;

  if v_next is null then
    raise exception 'No se puede avanzar desde el estado actual';
  end if;

  update public.orders
  set
    status = v_next,
    completed_at = case when v_next = 'completed' then now() else completed_at end
  where id = p_order_id
  returning * into v_order;

  return v_order;
end;
$$;

create or replace function public.advance_order(p_order_id uuid)
returns public.orders
language sql
security invoker
set search_path = public, private
as $$
  select * from private.advance_order_impl(p_order_id);
$$;

create or replace function private.cancel_order_impl(p_order_id uuid)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_order public.orders;
begin
  if v_uid is null then
    raise exception 'No autenticado';
  end if;

  update public.orders
  set status = 'cancelled'
  where id = p_order_id
    and client_id = v_uid
    and status in ('open', 'accepted')
  returning * into v_order;

  if v_order.id is null then
    raise exception 'El pedido ya no puede cancelarse';
  end if;

  return v_order;
end;
$$;

create or replace function public.cancel_order(p_order_id uuid)
returns public.orders
language sql
security invoker
set search_path = public, private
as $$
  select * from private.cancel_order_impl(p_order_id);
$$;

revoke all on function private.complete_profile_impl(text, text, text, text)
  from public, anon, authenticated;
revoke all on function private.accept_order_impl(uuid)
  from public, anon, authenticated;
revoke all on function private.advance_order_impl(uuid)
  from public, anon, authenticated;
revoke all on function private.cancel_order_impl(uuid)
  from public, anon, authenticated;

grant execute on function private.complete_profile_impl(text, text, text, text)
  to authenticated;
grant execute on function private.accept_order_impl(uuid)
  to authenticated;
grant execute on function private.advance_order_impl(uuid)
  to authenticated;
grant execute on function private.cancel_order_impl(uuid)
  to authenticated;

revoke all on function public.complete_profile(text, text, text, text)
  from public, anon;
revoke all on function public.accept_order(uuid)
  from public, anon;
revoke all on function public.advance_order(uuid)
  from public, anon;
revoke all on function public.cancel_order(uuid)
  from public, anon;

grant execute on function public.complete_profile(text, text, text, text)
  to authenticated;
grant execute on function public.accept_order(uuid)
  to authenticated;
grant execute on function public.advance_order(uuid)
  to authenticated;
grant execute on function public.cancel_order(uuid)
  to authenticated;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'orders'
    ) then
      alter publication supabase_realtime add table public.orders;
    end if;

    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'messages'
    ) then
      alter publication supabase_realtime add table public.messages;
    end if;
  end if;
exception
  when undefined_object then null;
end $$;
