-- V5 service catalog compatibility: stable slugs plus relational specialties.

update public.services
set slug = 'jardin', name = 'Jardinería', emoji = 'leaf', base_price = coalesce(base_price, 16000), active = true
where slug = 'jardineria'
  and not exists (select 1 from public.services where slug = 'jardin');

update public.services
set slug = 'electro', name = 'Electrodomésticos', emoji = 'plug', base_price = coalesce(base_price, 21000), active = true
where slug = 'electrodomesticos'
  and not exists (select 1 from public.services where slug = 'electro');

insert into public.services (slug, name, emoji, base_price, active) values
  ('plomeria', 'Plomería', 'wrench', 18000, true),
  ('electricidad', 'Electricidad', 'bolt', 20000, true),
  ('limpieza', 'Limpieza', 'sparkles', 15000, true),
  ('gas', 'Gasista', 'flame', 22000, true),
  ('cerrajeria', 'Cerrajería', 'key', 19000, true),
  ('pintura', 'Pintura', 'paint', 25000, true),
  ('jardin', 'Jardinería', 'leaf', 16000, true),
  ('arreglos', 'Arreglos', 'hammer', 17000, true),
  ('aire', 'Aire acondicionado', 'snowflake', 24000, true),
  ('electro', 'Electrodomésticos', 'plug', 21000, true),
  ('mudanzas', 'Mudanzas', 'truck', 30000, true),
  ('carpinteria', 'Carpintería', 'hammer', 23000, true),
  ('fumigacion', 'Fumigación', 'bug', 18000, true),
  ('tecnologia', 'PC y tecnología', 'monitor', 19000, true),
  ('albanileria', 'Albañilería', 'brick', 26000, true),
  ('pileta', 'Piletas', 'waves', 20000, true)
on conflict (slug) do update set
  name = excluded.name,
  emoji = excluded.emoji,
  base_price = excluded.base_price,
  active = true;

create table if not exists public.specialties (
  id bigint generated by default as identity primary key,
  service_id bigint not null references public.services(id) on delete cascade,
  name text not null,
  position integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (service_id, name),
  unique (id, service_id)
);

create table if not exists public.professional_specialties (
  professional_id uuid not null,
  service_id bigint not null,
  specialty_id bigint not null,
  created_at timestamptz not null default now(),
  primary key (professional_id, specialty_id),
  foreign key (professional_id, service_id)
    references public.professional_services(professional_id, service_id)
    on delete cascade,
  foreign key (specialty_id, service_id)
    references public.specialties(id, service_id)
    on delete cascade
);

create index if not exists idx_specialties_service
  on public.specialties(service_id, position, name)
  where active;

create index if not exists idx_professional_specialties_professional
  on public.professional_specialties(professional_id, service_id);

with catalog(slug, specialty_name, position) as (
  values
    ('plomeria', 'Pérdidas de agua', 1),
    ('plomeria', 'Destapaciones', 2),
    ('plomeria', 'Griferías', 3),
    ('plomeria', 'Sanitarios', 4),
    ('plomeria', 'Termotanques', 5),
    ('plomeria', 'Bombas de agua', 6),
    ('electricidad', 'Cortocircuitos', 1),
    ('electricidad', 'Tableros y térmicas', 2),
    ('electricidad', 'Tomas y enchufes', 3),
    ('electricidad', 'Iluminación', 4),
    ('electricidad', 'Cableado', 5),
    ('electricidad', 'Instalaciones', 6),
    ('limpieza', 'Limpieza general', 1),
    ('limpieza', 'Limpieza profunda', 2),
    ('limpieza', 'Post obra', 3),
    ('limpieza', 'Oficinas', 4),
    ('limpieza', 'Mudanzas', 5),
    ('gas', 'Calefones', 1),
    ('gas', 'Cocinas', 2),
    ('gas', 'Estufas', 3),
    ('gas', 'Pruebas de hermeticidad', 4),
    ('gas', 'Instalaciones de gas', 5),
    ('cerrajeria', 'Aperturas', 1),
    ('cerrajeria', 'Cambio de cerraduras', 2),
    ('cerrajeria', 'Llaves', 3),
    ('cerrajeria', 'Puertas blindadas', 4),
    ('cerrajeria', 'Urgencias', 5),
    ('pintura', 'Interiores', 1),
    ('pintura', 'Exteriores', 2),
    ('pintura', 'Techos', 3),
    ('pintura', 'Humedad', 4),
    ('pintura', 'Revestimientos', 5),
    ('jardin', 'Corte de césped', 1),
    ('jardin', 'Poda', 2),
    ('jardin', 'Mantenimiento', 3),
    ('jardin', 'Limpieza de terrenos', 4),
    ('jardin', 'Riego', 5),
    ('arreglos', 'Armado de muebles', 1),
    ('arreglos', 'Colocaciones', 2),
    ('arreglos', 'Perforaciones', 3),
    ('arreglos', 'Mantenimiento general', 4),
    ('arreglos', 'Montajes', 5),
    ('aire', 'Instalación de split', 1),
    ('aire', 'Limpieza', 2),
    ('aire', 'Carga de gas', 3),
    ('aire', 'Diagnóstico', 4),
    ('aire', 'Mantenimiento', 5),
    ('electro', 'Heladeras', 1),
    ('electro', 'Lavarropas', 2),
    ('electro', 'Hornos', 3),
    ('electro', 'Microondas', 4),
    ('electro', 'Diagnóstico de equipos', 5),
    ('mudanzas', 'Fletes', 1),
    ('mudanzas', 'Mudanzas completas', 2),
    ('mudanzas', 'Embalaje', 3),
    ('mudanzas', 'Armado y desarmado', 4),
    ('carpinteria', 'Muebles a medida', 1),
    ('carpinteria', 'Puertas', 2),
    ('carpinteria', 'Estantes', 3),
    ('carpinteria', 'Reparaciones', 4),
    ('fumigacion', 'Cucarachas', 1),
    ('fumigacion', 'Hormigas', 2),
    ('fumigacion', 'Roedores', 3),
    ('fumigacion', 'Desinsectación', 4),
    ('tecnologia', 'PC y notebooks', 1),
    ('tecnologia', 'Wi-Fi y redes', 2),
    ('tecnologia', 'Impresoras', 3),
    ('tecnologia', 'Instalación de software', 4),
    ('albanileria', 'Revoques', 1),
    ('albanileria', 'Pisos', 2),
    ('albanileria', 'Paredes', 3),
    ('albanileria', 'Reparaciones', 4),
    ('pileta', 'Limpieza', 1),
    ('pileta', 'Bombas', 2),
    ('pileta', 'Filtros', 3),
    ('pileta', 'Mantenimiento', 4)
)
insert into public.specialties (service_id, name, position, active)
select services.id, catalog.specialty_name, catalog.position, true
from catalog
join public.services on services.slug = catalog.slug
on conflict (service_id, name) do update set
  position = excluded.position,
  active = true;

alter table public.specialties enable row level security;
alter table public.professional_specialties enable row level security;

revoke all on public.specialties from anon, authenticated;
revoke all on public.professional_specialties from anon, authenticated;

grant select on public.specialties to authenticated;
grant select, insert, delete on public.professional_specialties to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists specialties_select on public.specialties;
create policy specialties_select on public.specialties
for select to authenticated
using (
  active = true
  and exists (
    select 1
    from public.services s
    where s.id = specialties.service_id
      and s.active = true
  )
);

drop policy if exists professional_specialties_select on public.professional_specialties;
create policy professional_specialties_select on public.professional_specialties
for select to authenticated
using (true);

drop policy if exists professional_specialties_insert_own on public.professional_specialties;
create policy professional_specialties_insert_own on public.professional_specialties
for insert to authenticated
with check (professional_id = (select auth.uid()));

drop policy if exists professional_specialties_delete_own on public.professional_specialties;
create policy professional_specialties_delete_own on public.professional_specialties
for delete to authenticated
using (professional_id = (select auth.uid()));
